sudo: false
dist: xenial
language: python
matrix:
    fast_finish: true
env:
    global:
        - THEANO_FLAGS=floatX=float64,compute_test_value=off
cache:
  directories:
  - "$HOME/.cache/pip"
jobs:
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'

install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install --upgrade setuptools
    - travis_retry pip install --upgrade -r requirements.txt
    - travis_retry python setup.py develop

script:
    - py.test -v -s volcano
